//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuyi.Oa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BikeInfo
    {
        public int ID { get; set; }
        public string UID { get; set; }
        public string Name { get; set; }
        public Nullable<short> DelFlag { get; set; }
        public System.DateTime SubTime { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public string AdminUser { get; set; }
        public int Counts { get; set; }
        public decimal Price { get; set; }
        public decimal TotalPrice { get; set; }
    }
}
